
export interface IPaydayEligibilityCheckResp{
    id: string,
    account_Number?: string,
    loan_Category?: string,
    repaymentMode?: number,
    eligible_Amount?: number,
    amount_Taken?: number,
    load_Date?: string,
    total_Eligible_Amount?: number,
    interestRate?: number,
    interestValue?: number,
    managementRate?: number,
    insuranceRate?: number,
    managementFlatFee?: number,
    insuranceFlatFee?: number,
    totalRate?: number,
    rateDuration?: string,
    tenor?: number,
    tenorMonth?: number,
    loanTerm?: string,
    serviceCharge?: number,
    dueDate?: string,
    pageName?: string,
    minAmount?: number,
    maxAmount?: number,
    doCreditCheck?: boolean,
    isTopUp?: boolean,
    loanScheme?: string,
    doCreditCheckMessage?: string,
    creditCheckPercentageAmount?: number,
    creditCheckFlatAmount?: number,
    message?: string,
    responseCode: string
}